// Language support with 6+ languages
export const SUPPORTED_LANGUAGES = {
  en: { name: "English", flag: "🇺🇸", nativeName: "English" },
  zh: { name: "Chinese", flag: "🇨🇳", nativeName: "中文" },
  ja: { name: "Japanese", flag: "🇯🇵", nativeName: "日本語" },
  ko: { name: "Korean", flag: "🇰🇷", nativeName: "한국어" },
  hi: { name: "Hindi", flag: "🇮🇳", nativeName: "हिन्दी" },
  tr: { name: "Turkish", flag: "🇹🇷", nativeName: "Türkçe" },
  es: { name: "Spanish", flag: "🇪🇸", nativeName: "Español" },
  fr: { name: "French", flag: "🇫🇷", nativeName: "Français" },
  de: { name: "German", flag: "🇩🇪", nativeName: "Deutsch" },
  pt: { name: "Portuguese", flag: "🇧🇷", nativeName: "Português" },
  ru: { name: "Russian", flag: "🇷🇺", nativeName: "Русский" },
  ar: { name: "Arabic", flag: "🇸🇦", nativeName: "العربية" },
};

export const TRANSLATIONS = {
  en: {
    // Profile
    profile: "Profile",
    customizeExperience: "Customize your experience",
    emotionalWavelenghts: "Exploring emotional wavelengths",
    moodOrbs: "Mood Orbs",
    connections: "Connections",
    daysActive: "Days Active",
    activity: "ACTIVITY",
    notifications: "Notifications",
    achievements: "Achievements",
    preferences: "PREFERENCES",
    pushNotifications: "Push Notifications",
    language: "Language",
    selectLanguage: "Select your preferred language",
    about: "ABOUT",
    aboutMindLink: "About MindLink",
    signOut: "Sign Out",

    // About MindLink
    aboutTitle: "About MindLink",
    aboutDescription:
      "MindLink is a revolutionary platform that connects people through their emotions and mental states. Our AI-powered mood orbs help you visualize and share your feelings in a beautiful, artistic way.",
    features: "Features:",
    feature1: "🎨 AI-powered mood visualization",
    feature2: "🌍 Multi-language emotional analysis",
    feature3: "🎵 Personalized music recommendations",
    feature4: "👥 Connect with like-minded souls",
    feature5: "📊 Track your emotional journey",
    feature6: "🏆 Achievement system for growth",
    createdBy: "Created with ❤️ by the MindLink Team",
    version: "MindLink v2.0",
    tagline: "Connect with souls on your wavelength",

    // General
    close: "Close",
    save: "Save",
    cancel: "Cancel",
    loading: "Loading...",
    welcome: "Welcome",
    hello: "Hello",
  },

  zh: {
    profile: "个人资料",
    customizeExperience: "定制您的体验",
    emotionalWavelenghts: "探索情感波长",
    moodOrbs: "心情球",
    connections: "连接",
    daysActive: "活跃天数",
    activity: "活动",
    notifications: "通知",
    achievements: "成就",
    preferences: "偏好",
    pushNotifications: "推送通知",
    language: "语言",
    selectLanguage: "选择您的首选语言",
    about: "关于",
    aboutMindLink: "关于心境链接",
    signOut: "退出登录",
    aboutTitle: "关于心境链接",
    aboutDescription:
      "心境链接是一个革命性的平台，通过情感和心理状态连接人们。我们的AI驱动的心情球帮助您以美丽、艺术的方式可视化和分享您的感受。",
    features: "功能：",
    feature1: "🎨 AI驱动的心情可视化",
    feature2: "🌍 多语言情感分析",
    feature3: "🎵 个性化音乐推荐",
    feature4: "👥 与志同道合的人连接",
    feature5: "📊 追踪您的情感之旅",
    feature6: "🏆 成长成就系统",
    createdBy: "由心境链接团队用 ❤️ 创建",
    version: "心境链接 v2.0",
    tagline: "与您波长相同的灵魂连接",
    close: "关闭",
    save: "保存",
    cancel: "取消",
    loading: "加载中...",
    welcome: "欢迎",
    hello: "你好",
  },

  ja: {
    profile: "プロフィール",
    customizeExperience: "エクスペリエンスをカスタマイズ",
    emotionalWavelenghts: "感情の波長を探索",
    moodOrbs: "ムードオーブ",
    connections: "つながり",
    daysActive: "アクティブ日数",
    activity: "アクティビティ",
    notifications: "通知",
    achievements: "実績",
    preferences: "設定",
    pushNotifications: "プッシュ通知",
    language: "言語",
    selectLanguage: "お好みの言語を選択",
    about: "について",
    aboutMindLink: "MindLinkについて",
    signOut: "サインアウト",
    aboutTitle: "MindLinkについて",
    aboutDescription:
      "MindLinkは、感情や精神状態を通じて人々をつなぐ革新的なプラットフォームです。AI駆動のムードオーブは、あなたの感情を美しく芸術的な方法で視覚化し、共有することを可能にします。",
    features: "機能：",
    feature1: "🎨 AI駆動のムード視覚化",
    feature2: "🌍 多言語感情分析",
    feature3: "🎵 パーソナライズされた音楽推薦",
    feature4: "👥 同じ志の人々とのつながり",
    feature5: "📊 感情の旅を追跡",
    feature6: "🏆 成長のための実績システム",
    createdBy: "MindLinkチームが ❤️ で作成",
    version: "MindLink v2.0",
    tagline: "同じ波長の魂とつながる",
    close: "閉じる",
    save: "保存",
    cancel: "キャンセル",
    loading: "読み込み中...",
    welcome: "ようこそ",
    hello: "こんにちは",
  },

  ko: {
    profile: "프로필",
    customizeExperience: "경험을 맞춤화하세요",
    emotionalWavelenghts: "감정적 파장 탐색",
    moodOrbs: "무드 오브",
    connections: "연결",
    daysActive: "활동 일수",
    activity: "활동",
    notifications: "알림",
    achievements: "업적",
    preferences: "환경설정",
    pushNotifications: "푸시 알림",
    language: "언어",
    selectLanguage: "선호하는 언어를 선택하세요",
    about: "정보",
    aboutMindLink: "MindLink 정보",
    signOut: "로그아웃",
    aboutTitle: "MindLink 정보",
    aboutDescription:
      "MindLink는 감정과 정신 상태를 통해 사람들을 연결하는 혁신적인 플랫폼입니다. AI 기반 무드 오브는 아름답고 예술적인 방식으로 감정을 시각화하고 공유할 수 있도록 도와줍니다.",
    features: "기능:",
    feature1: "🎨 AI 기반 무드 시각화",
    feature2: "🌍 다국어 감정 분석",
    feature3: "🎵 개인화된 음악 추천",
    feature4: "👥 같은 생각을 가진 영혼들과의 연결",
    feature5: "📊 감정 여정 추적",
    feature6: "🏆 성장을 위한 업적 시스템",
    createdBy: "MindLink 팀이 ❤️ 로 제작",
    version: "MindLink v2.0",
    tagline: "당신의 파장과 일치하는 영혼들과 연결",
    close: "닫기",
    save: "저장",
    cancel: "취소",
    loading: "로딩 중...",
    welcome: "환영합니다",
    hello: "안녕하세요",
  },

  hi: {
    profile: "प्रोफ़ाइल",
    customizeExperience: "अपना अनुभव अनुकूलित करें",
    emotionalWavelenghts: "भावनात्मक तरंग दैर्घ्य की खोज",
    moodOrbs: "मूड ऑर्ब",
    connections: "कनेक्शन",
    daysActive: "सक्रिय दिन",
    activity: "गतिविधि",
    notifications: "सूचनाएं",
    achievements: "उपलब्धियां",
    preferences: "प्राथमिकताएं",
    pushNotifications: "पुश सूचनाएं",
    language: "भाषा",
    selectLanguage: "अपनी पसंदीदा भाषा चुनें",
    about: "के बारे में",
    aboutMindLink: "MindLink के बारे में",
    signOut: "साइन आउट",
    aboutTitle: "MindLink के बारे में",
    aboutDescription:
      "MindLink एक क्रांतिकारी प्लेटफॉर्म है जो लोगों को उनकी भावनाओं और मानसिक अवस्थाओं के माध्यम से जोड़ता है। हमारे AI-संचालित मूड ऑर्ब आपको अपनी भावनाओं को सुंदर, कलात्मक तरीके से देखने और साझा करने में मदद करते हैं।",
    features: "विशेषताएं:",
    feature1: "🎨 AI-संचालित मूड दृश्यता",
    feature2: "🌍 बहुभाषी भावनात्मक विश्लेषण",
    feature3: "🎵 व्यक्तिगत संगीत सिफारिशें",
    feature4: "👥 समान विचारधारा वाली आत्माओं से जुड़ें",
    feature5: "📊 अपनी भावनात्मक यात्रा को ट्रैक करें",
    feature6: "🏆 विकास के लिए उपलब्धि प्रणाली",
    createdBy: "MindLink टीम द्वारा ❤️ के साथ बनाया गया",
    version: "MindLink v2.0",
    tagline: "अपनी तरंग दैर्घ्य पर आत्माओं से जुड़ें",
    close: "बंद करें",
    save: "सेव करें",
    cancel: "रद्द करें",
    loading: "लोड हो रहा है...",
    welcome: "स्वागत है",
    hello: "नमस्ते",
  },

  tr: {
    profile: "Profil",
    customizeExperience: "Deneyiminizi özelleştirin",
    emotionalWavelenghts: "Duygusal dalga boylarını keşfetme",
    moodOrbs: "Ruh Hali Küreleri",
    connections: "Bağlantılar",
    daysActive: "Aktif Günler",
    activity: "AKTİVİTE",
    notifications: "Bildirimler",
    achievements: "Başarılar",
    preferences: "TERCİHLER",
    pushNotifications: "Push Bildirimleri",
    language: "Dil",
    selectLanguage: "Tercih ettiğiniz dili seçin",
    about: "HAKKINDA",
    aboutMindLink: "MindLink Hakkında",
    signOut: "Çıkış Yap",
    aboutTitle: "MindLink Hakkında",
    aboutDescription:
      "MindLink, insanları duygular ve zihinsel durumları aracılığıyla birbirine bağlayan devrim niteliğinde bir platformdur. AI destekli ruh hali kürelerimiz, duygularınızı güzel ve sanatsal bir şekilde görselleştirmenize ve paylaşmanıza yardımcı olur.",
    features: "Özellikler:",
    feature1: "🎨 AI destekli ruh hali görselleştirme",
    feature2: "🌍 Çok dilli duygusal analiz",
    feature3: "🎵 Kişiselleştirilmiş müzik önerileri",
    feature4: "👥 Benzer düşünceli ruhlarla bağlan",
    feature5: "📊 Duygusal yolculuğunuzu takip edin",
    feature6: "🏆 Büyüme için başarı sistemi",
    createdBy: "MindLink Ekibi tarafından ❤️ ile oluşturuldu",
    version: "MindLink v2.0",
    tagline: "Dalga boyunuzdaki ruhlarla bağlanın",
    close: "Kapat",
    save: "Kaydet",
    cancel: "İptal",
    loading: "Yükleniyor...",
    welcome: "Hoş geldiniz",
    hello: "Merhaba",
  },
};

export const getTranslation = (language, key) => {
  return TRANSLATIONS[language]?.[key] || TRANSLATIONS.en[key] || key;
};

export const getCurrentLanguage = () => {
  if (typeof window !== "undefined") {
    return localStorage.getItem("mindlink_language") || "en";
  }
  return "en";
};

export const setLanguage = (language) => {
  if (typeof window !== "undefined") {
    localStorage.setItem("mindlink_language", language);
  }
};
